name: material_color_utilities
description: Algorithms and utilities that power the Material Design 3 (M3) color system, including choosing theme colors from images and creating tones of colors; all in a new color space.
version: 1.0.0
repository: https://github.com/deminearchiver/material-color-utilities-dart
homepage: https://github.com/deminearchiver/material-color-utilities
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - mtb

dependencies:
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.10.4
  collection: ^1.19.1
  deminearchiver_lints: ^1.1.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2
  test: ^1.28.0
